use std::{collections::HashMap, sync::LazyLock};

pub static BUTTON_SEQUENCES: LazyLock<HashMap<(u8, u8), Vec<u8>>> = LazyLock::new(|| {
    // As discussed at https://www.reddit.com/r/adventofcode/comments/1hj2odw/2024_day_21_solutions/
    // we should favour:
    // (i)   Consecutive presses
    // (ii)  b'<'
    // (iii) b'^' or b'v'
    // (iv)  b'>'
    HashMap::from([
        // A
        ((b'A', b'A'), vec![b'A', b'A']),
        ((b'A', b'0'), vec![b'A', b'<', b'A']),
        ((b'A', b'1'), vec![b'A', b'^', b'<', b'<', b'A']),
        ((b'A', b'2'), vec![b'A', b'<', b'^', b'A']),
        ((b'A', b'3'), vec![b'A', b'^', b'A']),
        ((b'A', b'4'), vec![b'A', b'^', b'^', b'<', b'<', b'A']),
        ((b'A', b'5'), vec![b'A', b'<', b'^', b'^', b'A']),
        ((b'A', b'6'), vec![b'A', b'^', b'^', b'A']),
        ((b'A', b'7'), vec![b'A', b'^', b'^', b'^', b'<', b'<', b'A']),
        ((b'A', b'8'), vec![b'A', b'<', b'^', b'^', b'^', b'A']),
        ((b'A', b'9'), vec![b'A', b'^', b'^', b'^', b'A']),
        // 0
        ((b'0', b'A'), vec![b'A', b'>', b'A']),
        ((b'0', b'0'), vec![b'A', b'A']),
        ((b'0', b'1'), vec![b'A', b'^', b'<', b'A']),
        ((b'0', b'2'), vec![b'A', b'^', b'A']),
        ((b'0', b'3'), vec![b'A', b'^', b'>', b'A']),
        ((b'0', b'4'), vec![b'A', b'^', b'^', b'<', b'A']),
        ((b'0', b'5'), vec![b'A', b'^', b'^', b'A']),
        ((b'0', b'6'), vec![b'A', b'^', b'^', b'>', b'A']),
        ((b'0', b'7'), vec![b'A', b'^', b'^', b'^', b'<', b'A']),
        ((b'0', b'8'), vec![b'A', b'^', b'^', b'^', b'A']),
        ((b'0', b'9'), vec![b'A', b'^', b'^', b'^', b'>', b'A']),
        // 1
        ((b'1', b'A'), vec![b'A', b'>', b'>', b'v', b'A']),
        ((b'1', b'0'), vec![b'A', b'>', b'v', b'A']),
        ((b'1', b'1'), vec![b'A', b'A']),
        ((b'1', b'2'), vec![b'A', b'>', b'A']),
        ((b'1', b'3'), vec![b'A', b'>', b'>', b'A']),
        ((b'1', b'4'), vec![b'A', b'^', b'A']),
        ((b'1', b'5'), vec![b'A', b'^', b'>', b'A']),
        ((b'1', b'6'), vec![b'A', b'^', b'>', b'>', b'A']),
        ((b'1', b'7'), vec![b'A', b'^', b'^', b'A']),
        ((b'1', b'8'), vec![b'A', b'^', b'^', b'>', b'A']),
        ((b'1', b'9'), vec![b'A', b'^', b'^', b'>', b'>', b'A']),
        // 2
        ((b'2', b'A'), vec![b'A', b'v', b'>', b'A']),
        ((b'2', b'0'), vec![b'A', b'v', b'A']),
        ((b'2', b'1'), vec![b'A', b'<', b'A']),
        ((b'2', b'2'), vec![b'A', b'A']),
        ((b'2', b'3'), vec![b'A', b'>', b'A']),
        ((b'2', b'4'), vec![b'A', b'<', b'^', b'A']),
        ((b'2', b'5'), vec![b'A', b'^', b'A']),
        ((b'2', b'6'), vec![b'A', b'^', b'>', b'A']),
        ((b'2', b'7'), vec![b'A', b'<', b'^', b'^', b'A']),
        ((b'2', b'8'), vec![b'A', b'^', b'^', b'A']),
        ((b'2', b'9'), vec![b'A', b'^', b'^', b'>', b'A']),
        // 3
        ((b'3', b'A'), vec![b'A', b'v', b'A']),
        ((b'3', b'0'), vec![b'A', b'<', b'v', b'A']),
        ((b'3', b'1'), vec![b'A', b'<', b'<', b'A']),
        ((b'3', b'2'), vec![b'A', b'<', b'A']),
        ((b'3', b'3'), vec![b'A', b'A']),
        ((b'3', b'4'), vec![b'A', b'<', b'<', b'^', b'A']),
        ((b'3', b'5'), vec![b'A', b'<', b'^', b'A']),
        ((b'3', b'6'), vec![b'A', b'^', b'A']),
        ((b'3', b'7'), vec![b'A', b'<', b'<', b'^', b'^', b'A']),
        ((b'3', b'8'), vec![b'A', b'<', b'^', b'^', b'A']),
        ((b'3', b'9'), vec![b'A', b'^', b'^', b'A']),
        // 4
        ((b'4', b'A'), vec![b'A', b'>', b'>', b'v', b'v', b'A']),
        ((b'4', b'0'), vec![b'A', b'>', b'v', b'v', b'A']),
        ((b'4', b'1'), vec![b'A', b'v', b'A']),
        ((b'4', b'2'), vec![b'A', b'v', b'>', b'A']),
        ((b'4', b'3'), vec![b'A', b'v', b'>', b'>', b'A']),
        ((b'4', b'4'), vec![b'A', b'A']),
        ((b'4', b'5'), vec![b'A', b'>', b'A']),
        ((b'4', b'6'), vec![b'A', b'>', b'>', b'A']),
        ((b'4', b'7'), vec![b'A', b'^', b'A']),
        ((b'4', b'8'), vec![b'A', b'^', b'>', b'A']),
        ((b'4', b'9'), vec![b'A', b'^', b'>', b'>', b'A']),
        // 5
        ((b'5', b'A'), vec![b'A', b'v', b'v', b'>', b'A']),
        ((b'5', b'0'), vec![b'A', b'v', b'v', b'A']),
        ((b'5', b'1'), vec![b'A', b'<', b'v', b'A']),
        ((b'5', b'2'), vec![b'A', b'v', b'A']),
        ((b'5', b'3'), vec![b'A', b'v', b'>', b'A']),
        ((b'5', b'4'), vec![b'A', b'<', b'A']),
        ((b'5', b'5'), vec![b'A', b'A']),
        ((b'5', b'6'), vec![b'A', b'>', b'A']),
        ((b'5', b'7'), vec![b'A', b'<', b'^', b'A']),
        ((b'5', b'8'), vec![b'A', b'^', b'A']),
        ((b'5', b'9'), vec![b'A', b'^', b'>', b'A']),
        // 6
        ((b'6', b'A'), vec![b'A', b'v', b'v', b'A']),
        ((b'6', b'0'), vec![b'A', b'<', b'v', b'v', b'A']),
        ((b'6', b'1'), vec![b'A', b'<', b'<', b'v', b'A']),
        ((b'6', b'2'), vec![b'A', b'<', b'v', b'A']),
        ((b'6', b'3'), vec![b'A', b'v', b'A']),
        ((b'6', b'4'), vec![b'A', b'<', b'<', b'A']),
        ((b'6', b'5'), vec![b'A', b'<', b'A']),
        ((b'6', b'6'), vec![b'A', b'A']),
        ((b'6', b'7'), vec![b'A', b'<', b'<', b'^', b'A']),
        ((b'6', b'8'), vec![b'A', b'<', b'^', b'A']),
        ((b'6', b'9'), vec![b'A', b'^', b'A']),
        // 7
        ((b'7', b'A'), vec![b'A', b'>', b'>', b'v', b'v', b'v', b'A']),
        ((b'7', b'0'), vec![b'A', b'>', b'v', b'v', b'v', b'A']),
        ((b'7', b'1'), vec![b'A', b'v', b'v', b'A']),
        ((b'7', b'2'), vec![b'A', b'v', b'v', b'>', b'A']),
        ((b'7', b'3'), vec![b'A', b'v', b'v', b'>', b'>', b'A']),
        ((b'7', b'4'), vec![b'A', b'v', b'A']),
        ((b'7', b'5'), vec![b'A', b'v', b'>', b'A']),
        ((b'7', b'6'), vec![b'A', b'v', b'>', b'>', b'A']),
        ((b'7', b'7'), vec![b'A', b'A']),
        ((b'7', b'8'), vec![b'A', b'>', b'A']),
        ((b'7', b'9'), vec![b'A', b'>', b'>', b'A']),
        // 8
        ((b'8', b'A'), vec![b'A', b'v', b'v', b'v', b'>', b'A']),
        ((b'8', b'0'), vec![b'A', b'v', b'v', b'v', b'A']),
        ((b'8', b'1'), vec![b'A', b'<', b'v', b'v', b'A']),
        ((b'8', b'2'), vec![b'A', b'v', b'v', b'A']),
        ((b'8', b'3'), vec![b'A', b'v', b'v', b'>', b'A']),
        ((b'8', b'4'), vec![b'A', b'<', b'v', b'A']),
        ((b'8', b'5'), vec![b'A', b'v', b'A']),
        ((b'8', b'6'), vec![b'A', b'v', b'>', b'A']),
        ((b'8', b'7'), vec![b'A', b'<', b'A']),
        ((b'8', b'8'), vec![b'A', b'A']),
        ((b'8', b'9'), vec![b'A', b'>', b'A']),
        // 9
        ((b'9', b'A'), vec![b'A', b'v', b'v', b'v', b'A']),
        ((b'9', b'0'), vec![b'A', b'<', b'v', b'v', b'v', b'A']),
        ((b'9', b'1'), vec![b'A', b'<', b'<', b'v', b'v', b'A']),
        ((b'9', b'2'), vec![b'A', b'<', b'v', b'v', b'A']),
        ((b'9', b'3'), vec![b'A', b'v', b'v', b'A']),
        ((b'9', b'4'), vec![b'A', b'<', b'<', b'v', b'A']),
        ((b'9', b'5'), vec![b'A', b'<', b'v', b'A']),
        ((b'9', b'6'), vec![b'A', b'v', b'A']),
        ((b'9', b'7'), vec![b'A', b'<', b'<', b'A']),
        ((b'9', b'8'), vec![b'A', b'<', b'A']),
        ((b'9', b'9'), vec![b'A', b'A']),
        // A
        ((b'A', b'A'), vec![b'A', b'A']),
        ((b'A', b'^'), vec![b'A', b'<', b'A']),
        ((b'A', b'>'), vec![b'A', b'v', b'A']),
        ((b'A', b'v'), vec![b'A', b'<', b'v', b'A']),
        ((b'A', b'<'), vec![b'A', b'v', b'<', b'<', b'A']),
        // ^
        ((b'^', b'A'), vec![b'A', b'>', b'A']),
        ((b'^', b'^'), vec![b'A', b'A']),
        ((b'^', b'>'), vec![b'A', b'v', b'>', b'A']),
        ((b'^', b'v'), vec![b'A', b'v', b'A']),
        ((b'^', b'<'), vec![b'A', b'v', b'<', b'A']),
        // >
        ((b'>', b'A'), vec![b'A', b'^', b'A']),
        ((b'>', b'^'), vec![b'A', b'<', b'^', b'A']),
        ((b'>', b'>'), vec![b'A', b'A']),
        ((b'>', b'v'), vec![b'A', b'<', b'A']),
        ((b'>', b'<'), vec![b'A', b'<', b'<', b'A']),
        // v
        ((b'v', b'A'), vec![b'A', b'^', b'>', b'A']),
        ((b'v', b'^'), vec![b'A', b'^', b'A']),
        ((b'v', b'>'), vec![b'A', b'>', b'A']),
        ((b'v', b'v'), vec![b'A', b'A']),
        ((b'v', b'<'), vec![b'A', b'<', b'A']),
        // <
        ((b'<', b'A'), vec![b'A', b'>', b'>', b'^', b'A']),
        ((b'<', b'^'), vec![b'A', b'>', b'^', b'A']),
        ((b'<', b'>'), vec![b'A', b'>', b'>', b'A']),
        ((b'<', b'v'), vec![b'A', b'>', b'A']),
        ((b'<', b'<'), vec![b'A', b'A']),
    ])
});
